services:

  twirp.service_registry:
    class: Twirfony\TwirfonyBundle\DependencyInjection\Twirp\ServiceRegistry
    public: true
    tags: ['routing.route_loader']


  Twirfony\TwirfonyBundle\Controller\TwirpController:
    tags: [controller.service_arguments]